# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pantry' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Digitales_Lager
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'



  target 'PantryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PantryUITests' do
    # Pods for testing
  end

end
